server:
  port: 19999

mysql:
  host: 127.0.0.1
  port: 3307
  dbname: go
  username: root 
  password: 123456

redis:
  host: 127.0.0.1
  port: 16379
  password: ""
  db: 0

jwt:
  secret: "syloe1-change-this-in-production"

rabbitmq:
  url: "amqp://guest:guest@127.0.0.1:5672/"
  exchange: "chat.events"
  queue: "group_message_push"
